server:
  port: 25532
spring:
  auto:
    openurl: true
  web:
    loginurl: http://localhost:25532
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:storage_info.db
    username:
    password:
  main:
    allow-circular-references: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.v3lmelt.LuoguCrawlerBackend.entity